In [4]:
from custom_ml import *
import gen as g
from sklearn.tree import DecisionTreeClassifier

In [24]:
df = g.user_vp_coupon_pref()

In [25]:
df.head()

REG_DATE SEX_ID  AGE WITHDRAW_DATE       PREF_NAME_x  \
0  2012-03-28 14:14:18      f   25           NaN               NaN   
1  2011-06-12 18:38:39      f   49           NaN  Hyogo Prefecture   
2  2011-07-29 18:02:46      f   25           NaN               NaN   
3  2012-03-29 14:08:37      f   38           NaN               NaN   
4  2011-07-17 00:00:15      m   34           NaN  Osaka prefecture   

                       USER_ID_hash  PURCHASE_FLG             I_DATE_x  \
0  d9dca3cb44bab12ba313eaa681f663eb             1  2012-03-28 15:06:11   
1  dd8a79645e8170db6a91bad1d89b4055             1  2012-03-26 23:26:26   
2  658249379aaaf2b2320061e5218c0c2c             1  2012-03-26 13:50:23   
3  e78ae0887c4a9dce91ff0d2a45a9f72c             1  2012-03-29 15:09:56   
4  fca1e37548c9ca5415a9850a1b9b2c28             1  2012-03-28 22:45:21   

   PAGE_SERIAL                     REFERRER_hash     ...      \
0           45  878034ded0ee2297d7ce27c5169e8584     ...       
1            7  6c5616ced18d79fa5a97c5c8f3e65f8f     ...       
2           12  6c5616ced18d79fa5a97c5c8f3e65f8f     ...       
3           60  6c5616ced18d79fa5a97c5c8f3e65f8f     ...       
4            9  6c5616ced18d79fa5a97c5c8f3e65f8f     ...       

  USABLE_DATE_HOLIDAY USABLE_DATE_BEFORE_HOLIDAY large_area_name  ken_name  \
0                 NaN                        NaN           Kanto     Tokyo   
1                 NaN                        NaN           Kanto     Tokyo   
2                 NaN                        NaN           Kanto     Tokyo   
3                 NaN                        NaN           Kanto     Tokyo   
4                 NaN                        NaN           Kanto     Tokyo   

                             small_area_name  \
0  Shinjuku, Takadanobaba Nakano - Kichijoji   
1  Shinjuku, Takadanobaba Nakano - Kichijoji   
2  Shinjuku, Takadanobaba Nakano - Kichijoji   
3  Shinjuku, Takadanobaba Nakano - Kichijoji   
4  Shinjuku, Takadanobaba Nakano - Kichijoji   

                   COUPON_ID_hash_y PREF_NAME_y PREFECTUAL_OFFICE   LATITUDE  \
0  34c48f84026e08355dc3bd19b427f09a       Tokyo          Shinjuku  35.689521   
1  34c48f84026e08355dc3bd19b427f09a       Tokyo          Shinjuku  35.689521   
2  34c48f84026e08355dc3bd19b427f09a       Tokyo          Shinjuku  35.689521   
3  34c48f84026e08355dc3bd19b427f09a       Tokyo          Shinjuku  35.689521   
4  34c48f84026e08355dc3bd19b427f09a       Tokyo          Shinjuku  35.689521   

    LONGITUDE  
0  139.691704  
1  139.691704  
2  139.691704  
3  139.691704  
4  139.691704  

[5 rows x 45 columns]

In [26]:
genre = df['GENRE_NAME']

In [27]:
genre.head()

0    Delivery service
1    Delivery service
2    Delivery service
3    Delivery service
4    Delivery service
Name: GENRE_NAME, dtype: object

In [28]:
X = df.loc[:,['AGE','DISCOUNT_PRICE']]

In [29]:
y = df.loc[:,'PURCHASE_FLG']

In [30]:
tree1 = DecisionTreeClassifier(criterion='entropy', max_depth=1, random_state=0).fit(X, y)

In [31]:
a, b = cls_conf(X, y,DecisionTreeClassifier(criterion='entropy', max_depth=1, random_state=0) )

In [32]:
tree1.score(X,y)

1.0

In [33]:
tree1.predict(X)

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [34]:
y

0         1
1         1
2         1
3         1
4         1
5         1
6         1
7         1
8         1
9         1
10        1
11        1
12        1
13        1
14        1
15        1
16        1
17        1
18        1
19        1
20        1
21        1
22        1
23        1
24        1
25        1
26        1
27        1
28        1
29        1
         ..
122359    1
122360    1
122361    1
122362    1
122363    1
122364    1
122365    1
122366    1
122367    1
122368    1
122369    1
122370    1
122371    1
122372    1
122373    1
122374    1
122375    1
122376    1
122377    1
122378    1
122379    1
122380    1
122381    1
122382    1
122383    1
122384    1
122385    1
122386    1
122387    1
122388    1
Name: PURCHASE_FLG, Length: 122389, dtype: int64

In [35]:
y.value_counts()

1    122389
Name: PURCHASE_FLG, dtype: int64

In [36]:
np.unique(tree1.predict(X))

array([1], dtype=int64)

In [37]:
df["PRICE_RATE"].as_matrix()[None].T.astype(np.float)

array([[78.],
       [78.],
       [78.],
       ...,
       [51.],
       [50.],
       [50.]])